name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { icon: '⬛', sys: mingw32, env: i686, use_32: True }
          - { icon: '🟦', sys: mingw64, env: x86_64, use_32: False }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: '${{ matrix.icon }} Setup MSYS2'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          release: false
          install: >-
            git
            make
            mingw-w64-${{matrix.env}}-toolchain
            mingw-w64-${{matrix.env}}-cmake
      - name: Configure CMake
        run: cmake -B build -G "CodeBlocks - MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_32BIT:bool=${{matrix.use_32}}
      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: build
        run: ctest -C ${{env.BUILD_TYPE}}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt-get update
      - name: Install freeglut package
        run: sudo apt-get install freeglut3-dev xorg-dev
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
